import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ActiveThemeProvider } from "@/components/active-theme";
import { cookies } from "next/headers";
import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";
const META_THEME_COLORS = {
  light: "#ffffff",
  dark: "#09090b",
}
export const metadata: Metadata = {
  title: "Dashboard Shadcn",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: META_THEME_COLORS.light,
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const activeThemeValue = cookieStore.get("active_theme")?.value
  const isScaled = activeThemeValue?.endsWith("-scaled")
  return (
    <html lang="en" suppressHydrationWarning>
      <body
className={cn(
  "bg-background overscroll-none font-sans antialiased",
  activeThemeValue ? `theme-${activeThemeValue}` : "",
  isScaled ? "theme-scaled" : "",
  fontVariables
)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ActiveThemeProvider initialTheme={activeThemeValue}>
            {children}
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
